[phases.setup]
nixPkgs = ["python311"]

[phases.install]
onlyIncludeFiles = ["requirements.txt", "forapitest.py", "Aptfile"]

[start]
cmd = "uvicorn forapitest:app --host 0.0.0.0 --port $PORT --workers 1"